# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-18 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_id', models.CharField(max_length=8)),
                ('name', models.TextField()),
                ('street', models.CharField(max_length=128)),
                ('postcode', models.SmallIntegerField()),
                ('city', models.CharField(max_length=128)),
                ('missed_date', models.DateField()),
            ],
        ),
    ]
