# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirkers', '0002_auto_20160925_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedMonths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missed_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='missed_date',
        ),
        migrations.AddField(
            model_name='missedmonths',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shirkers.Company'),
        ),
    ]
